shortname: director
domainname: servermain.local
stackhome: /home/stack

# Define the names of the source files that will be used to create
# to the destination system files instackenv.json and undercloud.conf
# respectively. If the role will be used on multiple sites then
# site names are encouraged. For example:
#
# instackenv-[SITE-NAME].sh
# undercloud-[SITE-NAME].conf

instackenv_sh: instackenv-servermain.sh
undercloud_conf: undercloud-servermain.conf

# Alternatively instackenv.json can be copied via template

# instackenv_json: instackenv-servermain.json
reg_script: files/addRepos-osp10.sh
